/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `menus` (
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(20) unsigned DEFAULT NULL,
  `isUiElement` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `icon` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=217 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `menus` DISABLE KEYS */;
INSERT INTO `menus` (`description`, `id`, `parent_id`, `isUiElement`, `name`, `created_at`, `updated_at`, `icon`, `link`) VALUES
	(NULL, 1, NULL, NULL, 'Tablero', '2021-06-12 20:36:00', '2021-07-12 20:36:01', 'ri-dashboard-line', '/'),
	(NULL, 2, NULL, NULL, 'CRM', NULL, NULL, 'fas fa-id-card', NULL),
	(NULL, 3, 2, NULL, 'Terceros', NULL, NULL, NULL, '/crm/terceros'),
	(NULL, 4, 2, NULL, 'Personas', NULL, NULL, NULL, '/crm/personas'),
	(NULL, 5, 2, NULL, 'APU', NULL, NULL, NULL, '/crm/apus'),
	(NULL, 6, 2, NULL, 'Presupuesto', NULL, NULL, NULL, '/crm/presupuesto'),
	(NULL, 7, NULL, NULL, 'Manufactura', NULL, NULL, 'fas fa-industry', NULL),
	(NULL, 8, NULL, NULL, 'Abastecimiento', NULL, NULL, 'fas fa-dolly-flatbed', NULL),
	(NULL, 9, 8, NULL, 'Órdenes de compra', NULL, NULL, NULL, '/compras/compra-nacional'),
	(NULL, 10, NULL, NULL, 'Almacén', NULL, NULL, 'fas fa-warehouse', NULL),
	('Historial Pago Nómina', 11, 10, NULL, 'Inventario', NULL, NULL, NULL, '/inventario/inventario'),
	('Inventario Fisico', 12, 10, NULL, 'Inventario físico', NULL, NULL, NULL, '/inventario/inventario-fisico'),
	('Inventario Fisico', 13, 10, NULL, 'Acta de recepción', NULL, NULL, NULL, '/inventario/acta-recepcion'),
	('Inventario Fisico', 14, 10, NULL, 'Inventario por vencer', NULL, NULL, NULL, '/inventario/vencer'),
	('Alistamiento', 15, 10, NULL, 'Alistamiento', NULL, NULL, NULL, '/inventario/alistamiento'),
	(NULL, 16, NULL, NULL, 'Logística', NULL, NULL, 'fas fa-truck', NULL),
	('Remisiones', 17, 16, NULL, 'Remisiones', NULL, NULL, NULL, '/inventario/remisiones'),
	(NULL, 18, NULL, NULL, 'RRHH', NULL, NULL, 'fas fa-users', NULL),
	(NULL, 19, 18, NULL, 'Horario', NULL, NULL, NULL, NULL),
	(NULL, 20, 18, NULL, 'Actividades', NULL, NULL, NULL, '/rrhh/actividades'),
	(NULL, 21, 18, NULL, 'Certificados', NULL, NULL, NULL, '/rrhh/certificados'),
	(NULL, 22, 18, NULL, 'Contratos', NULL, NULL, '', '/rrhh/contratos'),
	(NULL, 23, 18, NULL, 'Preliquidados', NULL, NULL, '', '/rrhh/liquidados'),
	(NULL, 24, 18, NULL, 'Novedades', NULL, NULL, '', '/rrhh/novedades'),
	(NULL, 25, 19, NULL, 'Llegadas tarde', NULL, NULL, '', '/rrhh/llegadas-tarde'),
	(NULL, 26, 19, NULL, 'Reporte de horarios', NULL, NULL, '', '/rrhh/turnos/reporte'),
	('Validación horas extras', 27, 18, NULL, 'Horas extra', NULL, NULL, NULL, NULL),
	(NULL, 28, 18, NULL, 'Dotación y EPP', NULL, NULL, NULL, NULL),
	(NULL, 29, 28, NULL, 'Dotaciones', NULL, NULL, '', '/rrhh/dotacion/dotaciones'),
	(NULL, 30, 28, NULL, 'Inventario', NULL, NULL, '', '/rrhh/dotacion/inventario'),
	(NULL, 31, 18, NULL, 'Procesos', NULL, NULL, NULL, NULL),
	(NULL, 32, 31, NULL, 'Disciplinarios', NULL, NULL, NULL, '/rrhh/procesos/disciplinarios'),
	(NULL, 33, 31, NULL, 'Memorandos', NULL, NULL, NULL, '/rrhh/procesos/memorandos'),
	(NULL, 34, 19, NULL, 'Asignación de turnos', NULL, NULL, NULL, '/rrhh/turnos/asignacion'),
	(NULL, 35, 18, NULL, 'Alertas - Común', NULL, NULL, NULL, '/rrhh/alertas-comun'),
	(NULL, 36, 18, NULL, 'Almuerzos', NULL, NULL, NULL, '/rrhh/almuerzos'),
	(NULL, 37, NULL, NULL, 'Nómina', NULL, NULL, 'fas fa-wallet', NULL),
	(NULL, 38, 37, NULL, 'Prestamos y libranzas', NULL, NULL, NULL, '/nomina/prestamos'),
	(NULL, 39, 37, NULL, 'Viáticos', NULL, NULL, NULL, '/nomina/viaticos'),
	('71', 40, 37, NULL, 'Pago de nómina', NULL, NULL, NULL, '/nomina/nomina'),
	(NULL, 41, 37, NULL, 'Pago de vacaciones', NULL, NULL, NULL, '/nomina/vacaciones'),
	(NULL, 42, 37, NULL, 'Primas', NULL, NULL, NULL, '/nomina/primas'),
	('Historial Pago Nómina', 43, 37, NULL, 'Historial de pago \r\nde nómina', NULL, NULL, NULL, '/nomina/historial-pagos'),
	(NULL, 44, NULL, NULL, 'Contabilidad', NULL, NULL, 'fas fa-calculator', NULL),
	(NULL, 45, 44, NULL, 'Plan cuentas', NULL, NULL, NULL, '/contabilidad/plan-cuentas'),
	(NULL, 46, 44, NULL, 'Centro costo', NULL, NULL, NULL, '/contabilidad/centro-costos'),
	(NULL, 47, 44, NULL, 'Depreciaciones', NULL, NULL, NULL, '/contabilidad/depreciaciones'),
	(NULL, 48, 44, NULL, 'Cajas', NULL, NULL, NULL, '/contabilidad/cajas'),
	(NULL, 49, 44, NULL, 'Activos fijos', NULL, NULL, NULL, '/contabilidad/activos-fijos'),
	(NULL, 50, 44, NULL, 'Comprobantes', NULL, NULL, NULL, NULL),
	(NULL, 51, 50, NULL, 'Notas contables', NULL, NULL, NULL, '/contabilidad/comprobantes/notas-contables'),
	(NULL, 52, 50, NULL, 'Egresos', NULL, NULL, NULL, '/contabilidad/comprobantes/egresos'),
	(NULL, 53, 50, NULL, 'Ingresos', NULL, NULL, NULL, '/contabilidad/comprobantes/ingresos'),
	(NULL, 54, 50, NULL, 'Notas cartera', NULL, NULL, NULL, '/contabilidad/comprobantes/notas-cartera'),
	(NULL, 55, 50, NULL, 'Notas crédito', NULL, NULL, NULL, '/contabilidad/comprobantes/notas-credito'),
	(NULL, 56, 44, NULL, 'Balances', NULL, NULL, NULL, NULL),
	(NULL, 57, 56, NULL, 'General', NULL, NULL, NULL, '/contabilidad/balances/general'),
	(NULL, 58, 56, NULL, 'Movimiento globalizado', NULL, NULL, NULL, '/contabilidad/balances/movimiento-globalizado'),
	(NULL, 59, 44, NULL, 'Estados', NULL, NULL, NULL, NULL),
	(NULL, 60, 59, NULL, 'Estados resultantes', NULL, NULL, NULL, '/contabilidad/estados/estados-resultantes'),
	(NULL, 61, 44, NULL, 'Informes DIAN', NULL, NULL, NULL, NULL),
	(NULL, 62, 61, NULL, 'Medios magnéticos básicos', NULL, NULL, NULL, '/contabilidad/informesdian/mediosmagneticos'),
	(NULL, 63, 61, NULL, 'Medios magnéticos especiales', NULL, NULL, NULL, '/contabilidad/informesdian/mediosmagneticosespeciales'),
	(NULL, 64, 61, NULL, 'Certificados de retención', NULL, NULL, NULL, '/contabilidad/informesdian/certificadoretencion'),
	(NULL, 65, 61, NULL, 'Certificados de ingreso y retención', NULL, NULL, NULL, '/contabilidad/informesdian/certificadoingresoyretencion'),
	(NULL, 66, 61, NULL, 'Agrupar formatos especiales', NULL, NULL, NULL, '/contabilidad/informesdian/agruparmediosmagneticos'),
	(NULL, 67, 61, NULL, 'Resumen de retenciones', NULL, NULL, NULL, '/contabilidad/informesdian/resumenretenciones'),
	(NULL, 68, 44, NULL, 'Cierres contables', NULL, NULL, NULL, '/contabilidad/cierres-contables'),
	(NULL, 69, NULL, NULL, 'Ajustes', NULL, NULL, 'fas fa-cog', NULL),
	(NULL, 70, 69, NULL, 'Parámetros', NULL, NULL, 'ri-map-pin-line', ''),
	(NULL, 71, 70, NULL, 'Parámetros APU', NULL, NULL, NULL, NULL),
	(NULL, 72, 71, NULL, 'Geometrías', NULL, NULL, NULL, '/ajustes/parametros/apu/geometrias'),
	(NULL, 73, 71, NULL, 'Materiales', NULL, NULL, NULL, '/ajustes/parametros/apu/materiales'),
	(NULL, 74, 71, NULL, 'Unidades de medidas', NULL, NULL, NULL, '/ajustes/parametros/apu/unidades-medidas'),
	(NULL, 75, 71, NULL, 'Variables APU', NULL, NULL, NULL, '/ajustes/parametros/apu/variables-apu'),
	(NULL, 76, 71, NULL, 'Costos indirectos', NULL, NULL, NULL, '/ajustes/parametros/apu/costos-indirectos'),
	(NULL, 77, 71, NULL, 'Medidas', NULL, NULL, NULL, '/ajustes/parametros/apu/medidas'),
	(NULL, 78, 71, NULL, 'Corte laser material', NULL, NULL, NULL, '/ajustes/parametros/apu/corte-laser-material'),
	(NULL, 79, 71, NULL, 'Espesores', NULL, NULL, NULL, '/ajustes/parametros/apu/espesores'),
	(NULL, 80, 71, NULL, 'Perfiles APU', NULL, NULL, NULL, '/ajustes/parametros/apu/perfiles'),
	(NULL, 81, 71, NULL, 'Estimación viáticos', NULL, NULL, NULL, '/ajustes/parametros/apu/estimacion-viaticos'),
	(NULL, 82, 71, NULL, 'Est. viáticos valores', NULL, NULL, NULL, '/ajustes/parametros/apu/est-viaticos-valores'),
	(NULL, 83, 70, NULL, 'Vacantes', NULL, NULL, NULL, 'ajustes/parametros/vacantes'),
	(NULL, 97, 69, NULL, 'Información base', NULL, NULL, NULL, NULL),
	(NULL, 98, 97, NULL, 'Empresa', NULL, NULL, NULL, 'ajustes/configuracion/configuracion-empresa/informacion'),
	(NULL, 100, 97, NULL, 'Funcionarios', NULL, NULL, NULL, '/ajustes/informacion-base/funcionarios'),
	(NULL, 102, 97, NULL, 'Turnos', NULL, NULL, NULL, '/ajustes/informacion-base/turnos'),
	(NULL, 103, 97, NULL, 'Bodegas', NULL, NULL, NULL, '/ajustes/informacion-base/bodegas'),
	(NULL, 106, 10, NULL, 'Catálogo', NULL, NULL, NULL, '/ajustes/informacion-base/catalogo'),
	(NULL, 107, 69, NULL, 'Tipos', NULL, NULL, NULL, NULL),
	(NULL, 108, 70, NULL, 'Contratos laborales', NULL, NULL, NULL, '/ajustes/tipos/contrato'),
	(NULL, 117, 107, NULL, 'Tipos retenciones', NULL, NULL, NULL, '/ajustes/tipos/tipos-retenciones'),
	(NULL, 120, 69, NULL, 'Configuración', NULL, NULL, NULL, NULL),
	(NULL, 125, 120, NULL, 'Config nómina', NULL, NULL, NULL, '/ajustes/configuracion/configuracion-nomina'),
	(NULL, 126, 71, NULL, 'Config base cálculos', NULL, NULL, NULL, '/ajustes/configuracion/base-calculos'),
	(NULL, 200, 70, NULL, 'Viáticos.', NULL, NULL, NULL, '/ajustes/parametros/viaticos'),
	(NULL, 207, 2, NULL, 'Negocios', NULL, NULL, NULL, '/crm/negocios'),
	(NULL, 208, 7, NULL, 'Prueba manufactura', NULL, NULL, NULL, '/manufactura/prueba'),
	(NULL, 211, 27, NULL, 'Asignación', NULL, NULL, NULL, '/rrhh/asignar-horas-extras'),
	(NULL, 212, 27, NULL, 'Validación', NULL, NULL, NULL, '/rrhh/turnos/horas-extras'),
	(NULL, 213, 18, NULL, 'Vacantes', NULL, NULL, '', '/rrhh/vacantes'),
	(NULL, 214, 70, NULL, 'Nómina', '2022-10-21 14:52:43', '2022-10-21 14:52:44', NULL, '/ajustes/parametros/nomina'),
	(NULL, 215, 120, NULL, 'Ubicaciones', '2022-10-21 17:38:36', '2022-10-21 17:38:37', NULL, '/ajustes/configuracion/ubicaciones'),
	(NULL, 216, 70, NULL, 'Terceros', '2022-11-02 08:43:27', '2022-11-02 08:43:28', NULL, '/ajustes/parametros/terceros');
/*!40000 ALTER TABLE `menus` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `menu_permission` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menu_id` int(11) DEFAULT NULL,
  `permission_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=144 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

/*!40000 ALTER TABLE `menu_permission` DISABLE KEYS */;
INSERT INTO `menu_permission` (`id`, `menu_id`, `permission_id`, `created_at`, `updated_at`) VALUES
	(1, 1, 1, NULL, NULL),
	(2, 2, 1, NULL, NULL),
	(3, 3, 1, NULL, NULL),
	(4, 4, 1, NULL, NULL),
	(5, 5, 1, NULL, NULL),
	(6, 6, 1, NULL, NULL),
	(7, 7, 1, NULL, NULL),
	(8, 8, 1, NULL, NULL),
	(9, 9, 1, NULL, NULL),
	(10, 10, 1, NULL, NULL),
	(11, 11, 1, NULL, NULL),
	(12, 12, 1, NULL, NULL),
	(13, 13, 1, NULL, NULL),
	(14, 14, 1, NULL, NULL),
	(15, 15, 1, NULL, NULL),
	(16, 16, 1, NULL, NULL),
	(17, 17, 1, NULL, NULL),
	(18, 18, 1, NULL, NULL),
	(19, 19, 1, NULL, NULL),
	(20, 20, 1, NULL, NULL),
	(21, 21, 1, NULL, NULL),
	(22, 22, 1, NULL, NULL),
	(23, 23, 1, NULL, NULL),
	(24, 24, 1, NULL, NULL),
	(25, 25, 1, NULL, NULL),
	(26, 26, 1, NULL, NULL),
	(27, 27, 1, NULL, NULL),
	(28, 28, 1, NULL, NULL),
	(29, 29, 1, NULL, NULL),
	(30, 30, 1, NULL, NULL),
	(31, 31, 1, NULL, NULL),
	(32, 32, 1, NULL, NULL),
	(33, 33, 1, NULL, NULL),
	(34, 34, 1, NULL, NULL),
	(35, 35, 1, NULL, NULL),
	(36, 36, 1, NULL, NULL),
	(37, 37, 1, NULL, NULL),
	(38, 38, 1, NULL, NULL),
	(39, 39, 1, NULL, NULL),
	(40, 40, 1, NULL, NULL),
	(41, 41, 1, NULL, NULL),
	(42, 42, 1, NULL, NULL),
	(43, 43, 1, NULL, NULL),
	(44, 44, 1, NULL, NULL),
	(45, 45, 1, NULL, NULL),
	(46, 46, 1, NULL, NULL),
	(47, 47, 1, NULL, NULL),
	(48, 48, 1, NULL, NULL),
	(49, 49, 1, NULL, NULL),
	(50, 50, 1, NULL, NULL),
	(51, 51, 1, NULL, NULL),
	(52, 52, 1, NULL, NULL),
	(53, 53, 1, NULL, NULL),
	(54, 54, 1, NULL, NULL),
	(55, 55, 1, NULL, NULL),
	(56, 56, 1, NULL, NULL),
	(57, 57, 1, NULL, NULL),
	(58, 58, 1, NULL, NULL),
	(59, 59, 1, NULL, NULL),
	(60, 60, 1, NULL, NULL),
	(61, 61, 1, NULL, NULL),
	(62, 62, 1, NULL, NULL),
	(63, 63, 1, NULL, NULL),
	(64, 64, 1, NULL, NULL),
	(65, 65, 1, NULL, NULL),
	(66, 66, 1, NULL, NULL),
	(67, 67, 1, NULL, NULL),
	(68, 68, 1, NULL, NULL),
	(69, 69, 1, NULL, NULL),
	(70, 70, 1, NULL, NULL),
	(71, 71, 1, NULL, NULL),
	(72, 72, 1, NULL, NULL),
	(73, 73, 1, NULL, NULL),
	(74, 74, 1, NULL, NULL),
	(75, 75, 1, NULL, NULL),
	(76, 76, 1, NULL, NULL),
	(77, 77, 1, NULL, NULL),
	(78, 78, 1, NULL, NULL),
	(79, 79, 1, NULL, NULL),
	(80, 80, 1, NULL, NULL),
	(81, 81, 1, NULL, NULL),
	(82, 82, 1, NULL, NULL),
	(83, 83, 1, NULL, NULL),
	(84, 84, 1, NULL, NULL),
	(86, 86, 1, NULL, NULL),
	(88, 88, 1, NULL, NULL),
	(89, 89, 1, NULL, NULL),
	(90, 90, 1, NULL, NULL),
	(91, 91, 1, NULL, NULL),
	(94, 94, 2, NULL, NULL),
	(95, 95, 1, NULL, NULL),
	(96, 96, 1, NULL, NULL),
	(97, 97, 1, NULL, NULL),
	(98, 98, 1, NULL, NULL),
	(99, 99, 1, NULL, NULL),
	(100, 100, 1, NULL, NULL),
	(101, 101, 1, NULL, NULL),
	(102, 102, 1, NULL, NULL),
	(103, 103, 1, NULL, NULL),
	(106, 106, 1, NULL, NULL),
	(107, 107, 1, NULL, NULL),
	(108, 108, 1, NULL, NULL),
	(109, 109, 1, NULL, NULL),
	(110, 110, 1, NULL, NULL),
	(111, 111, 1, NULL, NULL),
	(112, 112, 1, NULL, NULL),
	(113, 113, 1, NULL, NULL),
	(114, 114, 1, NULL, NULL),
	(115, 115, 1, NULL, NULL),
	(116, 116, 1, NULL, NULL),
	(117, 117, 1, NULL, NULL),
	(118, 118, 1, NULL, NULL),
	(119, 119, 1, NULL, NULL),
	(120, 120, 1, NULL, NULL),
	(121, 121, 1, NULL, NULL),
	(123, 123, 1, NULL, NULL),
	(124, 124, 1, NULL, NULL),
	(125, 125, 1, NULL, NULL),
	(126, 126, 1, NULL, NULL),
	(127, 200, 1, NULL, NULL),
	(128, 201, 1, NULL, NULL),
	(129, 202, 1, NULL, NULL),
	(130, 207, 1, NULL, NULL),
	(131, 208, 1, NULL, NULL),
	(132, 209, 1, NULL, NULL),
	(133, 210, 1, NULL, NULL),
	(134, 211, 1, NULL, NULL),
	(135, 212, 1, NULL, NULL),
	(136, 213, 1, NULL, NULL),
	(137, 33, 2, NULL, NULL),
	(138, 33, 3, NULL, NULL),
	(139, 33, 4, NULL, NULL),
	(140, 214, 1, NULL, NULL),
	(141, 215, 1, NULL, NULL),
	(142, 216, 1, NULL, NULL),
	(143, 39, 2, NULL, NULL);
/*!40000 ALTER TABLE `menu_permission` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
